POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNyaHFtcCIsImlkIjoiNjYzZTU5YjUyZTcwYzcxYTdjNzQwZDQwIiwiaWF0IjoxNzE1NDEyMDU3fQ.rD2l9KmThpckrqsCLwJPquWLrGCvNgbwcUrOG5zH6ks

{
    "title": "Ikaw Pa Rin",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 0
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My Second Blog",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 12
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A Blog",
    "author": "Gladys",
    "url": "https://www.google.com",
    "likes": 3
}