POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Ere",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 0,
    "userId": "663e59b52e70c71a7c740d40"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My Second Blog",
    "author": "Sarah",
    "url": "https://www.google.com",
    "likes": 12
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A Blog",
    "author": "Gladys",
    "url": "https://www.google.com",
    "likes": 3
}